server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # 将 /api/ 开头的请求转发到 backend 容器的 5000 端口
    location /api/ {
        proxy_pass http://backend:5000/api/;
    }
}