apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        # 反向代理到内部的 backend-svc (端口已修改为 5001)
        location /api/ {
            proxy_pass http://backend-svc:5001/api/;
        }
    }
