apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-disk-topology    # 华为云 EVS StorageClass
  resources:
    requests:
      storage: 10Gi